// Code generated by Kitex v0.5.2. DO NOT EDIT.
package greetingservice

import (
	server "github.com/cloudwego/kitex/server"
	greeting "github.com/invictus555/auto_codes/greeting_service_v1/kitex_gen/greeting"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler greeting.GreetingService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
